#pragma once

typedef enum keyword_e{
    KEYWORD_IF,
    KEYWORD_ELSE,
    KEYWORD_RETURN,
    KEYWORD_SWITCH,
    KEYWORD_CASE,
    KEYWORD_WHILE,
    KEYWORD_FOR,
    KEYWORD_STRUCT,
    KEYWORD_ENUM,
    KEYWORD_UNION,
    KEYWORD_BREAK,
    KEYWORD_CONTINUE,
    KEYWORD_INLINE,
    KEYWORD_CONST,
    KEYWORD_CAST,
    KEYWORD_STATIC,
    KEYWORD_TYPEDEF,
    KEYWORD_LABEL,
    KEYWORD_GOTO,
    KEYWORDS_ENUM_MAX,
}keyword;