#include "token_strings.h"
const char* token_strings[255] = {
    [TOKEN_MINUS_EQUALS] = "-=",
    [TOKEN_PLUS_EQUALS] = "+=",
    [TOKEN_STAR_EQUALS] = "*=",
    [TOKEN_EQUALS] = "=",
    [TOKEN_DOUBLE_EQUALS] = "==",
    [TOKEN_EXCLAMATION_MARK] = "!=",
    [TOKEN_EXCLAMATION_MARK_EQUALS] = "!=",
    [TOKEN_PERCENT] = "%",
    [TOKEN_PERCENT_EQUALS] = "%=",
    [TOKEN_SLASH] = "/",
    [TOKEN_SLASH_EQUALS] = "/=",
    [TOKEN_LESS_THAN] = "<",
    [TOKEN_LESS_THAN_EQUALS] = "<=",
    [TOKEN_DOUBLE_LESS_THAN] = "<<",
    [TOKEN_DOUBLE_LESS_THAN_EQUALS] = "<<=",
    [TOKEN_GREATER_THAN] = ">",
    [TOKEN_GREATER_THAN_EQUALS] = ">=",
    [TOKEN_DOUBLE_GREATER_THAN] = ">>",
    [TOKEN_DOUBLE_GREATER_THAN_EQUALS] = ">>=",
    [TOKEN_AND] = "&",
    [TOKEN_DOUBLE_AND] = "&&",
    [TOKEN_AND_EQUALS] = "&=",
    [TOKEN_PIPE] = "|",
    [TOKEN_DOUBLE_PIPE] = "||",
    [TOKEN_PIPE_EQUALS] = "|=",
    [TOKEN_CARET] = "^",
    [TOKEN_DOUBLE_CARET] = "^^",
    [TOKEN_CARET_EQUALS] = "^=",
    [TOKEN_TILDE] = "~",
    [TOKEN_TILDE_EQUALS] = "~=",

    [TOKEN_NUMBER] = 0,
    [TOKEN_LITERAL] = 0,
    [TOKEN_BINARY_LITERAL] = 0,
    [TOKEN_STRING] = 0,
    [TOKEN_EOF] = 0,

    [TOKEN_PLUS] = "+",
    [TOKEN_DOUBLE_PLUS] = "++",
    [TOKEN_MINUS] = "-",
    [TOKEN_DOUBLE_MINUS] = "--",
    [TOKEN_STAR] = "*",
    [TOKEN_PAREN_OPEN] = "(",
    [TOKEN_PAREN_CLOSE] = ")",
    [TOKEN_BRACKET_OPEN] = "[",
    [TOKEN_BRACKET_CLOSE] = "]",
    [TOKEN_BRACE_OPEN] = "{",
    [TOKEN_BRACE_CLOSE] = "}",

    [TOKEN_DOLLAR] = "$",
    [TOKEN_COMMA] = ",",
    [TOKEN_SEMICOLON] = ";",
    [TOKEN_HASH] = "#",
    [TOKEN_DOUBLE_HASH] = "##",
    [TOKEN_DOT] = ".",
    [TOKEN_COLON] = ":",
    [TOKEN_DOUBLE_COLON] = "::",
    [TOKEN_ARROW] = "->",
    [TOKEN_LEFT_ARROW] = "<==",
};