#pragma once
#include "keywords.h"
//we abuse the keywords for their pointer values,
// to ensure we don't overlap useful pointers

#define TYPE_TYPE_FN_PTR KEYWORD_IF
#define TYPE_TYPE_FN_MULTI_PTR KEYWORD_ELSE

#define TYPE_TYPE_SYMBOL KEYWORD_RETURN
#define TYPE_TYPE_SYMBOL_PTR KEYWORD_SWITCH
#define TYPE_TYPE_SYMBOL_MULTI_PTR KEYWORD_CASE

#define TYPE_TYPE_SCOPED_SYMBOL KEYWORD_WHILE
#define TYPE_TYPE_SCOPED_SYMBOL_PTR KEYWORD_FOR
#define TYPE_TYPE_SCOPED_SYMBOL_MULTI_PTR KEYWORD_STRUCT

#define TYPE_TYPE_GENERIC_STRUCT KEYWORD_ENUM
#define TYPE_TYPE_GENERIC_STRUCT_PTR KEYWORD_UNION
#define TYPE_TYPE_GENERIC_STRUCT_MULTI_PTR KEYWORD_BREAK

#define TYPE_TYPE_SCOPED_GENERIC_STRUCT KEYWORD_CONTINUE
#define TYPE_TYPE_SCOPED_GENERIC_STRUCT_PTR KEYWORD_INLINE
#define TYPE_TYPE_SCOPED_GENERIC_STRUCT_MULTI_PTR KEYWORD_CONST
